[package]
name = "hp-tracerled-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.15", features = ["derive"] }
hidapi = "2.6.3"
strum = { version = "0.26.3", features = ["derive"] }
